---
permalink: api-changes.html 
sidebar: sidebar 
keywords: rest api, api changes, parameters, default values, breaking changes, documentation errors 
summary: NetApp 持續在每個主要產品版本中增強及更新 ONTAP REST API 。這些更新有時可能會包括對現有 API 呼叫的變更、例如所使用的參數和預設值。這些變更可能會影響存取 REST API 的軟體。 
---
= ONTAP REST API 呼叫的變更
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp 持續在每個主要產品版本中增強及更新 ONTAP REST API 。這些更新有時可能會包括對現有 API 呼叫的變更、例如所使用的參數和預設值。這些變更可能會影響存取 REST API 的軟體。



== 變更現有的 ONTAP REST API 呼叫

對現有 API 呼叫所做的任何變更、都可能影響存取 REST API 的軟體。您應檢閱下表中的變更清單、以判斷是否會對 ONTAP 自動化環境造成影響。每個項目都包含適用的 API 端點、變更說明、以及推出的 ONTAP 版本。

[cols="40%,50%,10%"]
|===
| 端點 | 變更說明 | 發行版ONTAP 


| `/security/authentication/duo/groups`
`/security/authentication/duo/profiles` | 回應中的欄位 *_links * 已從這些端點的 duogroup 中移除。沒有建議客戶採取的行動或因應措施。此欄位預期會在未來的 ONTAP 版本中重新新增。 | 9.15.1.. 
|===


== ONTAP REST API 參考文件錯誤

隨著 NetApp 增強及更新 ONTAP REST API 、有時可能會在線上參考文件中出現錯誤。使用 API 時、這些錯誤可能會造成混淆、但通常不會影響或中斷 ONTAP 自動化軟體或環境。

您應檢閱下表中的錯誤清單。這將有助於您更深入瞭解及瀏覽 ONTAP REST API 參考文件。每個項目都包含適用的 API 端點、錯誤說明、以及所推出的 ONTAP 版本。

[cols="40%,50%,10%"]
|===
| 端點 | 變更說明 | 發行版ONTAP 


| `/storage/quota/reports` | 端點的 REST API 文件指出 * 規範 * 是有效欄位。不過、此端點不支援配額說明符。沒有建議客戶採取的行動或因應措施。此欄位將在未來的 ONTAP 版本中從 API 文件中移除。 | 9.6 
|===
.相關資訊
link:whats-new.html["更新功能ONTAP"]
