---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: 自動化文件ONTAP
    url: "/index.html"
  - section: rn
  - section: get-started
  - section: rest
  - section: workflows
  - section: manage
  - section: python
  - section: reference
  - section: automate
  - section: migrate
  - section: additional
  - title: 法律聲明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 開始使用
    links:
    - title: 版本資訊
      url: "/rn/whats_new.html"
    - title: 自動化選項ONTAP
      url: "/get-started/ontap_automation_options.html"
    - title: 準備使用REST API
      url: "/get-started/prepare.html"
    - title: 您的第一個API呼叫
      url: "/get-started/first_call.html"
  - title: 靜態API ONTAP
    links:
    - title: REST實作詳細資料
      url: "/rest/rest_web_services_foundation.html"
    - title: 其他考量
      url: "/rest/object_references_and_access.html"
    - title: 剩餘資源摘要
      url: "/resources/overview_categories.html"
    - title: API 參考
      url: "/reference/api_reference.html"
  - title: 自動化
    links:
    - title: Python用戶端程式庫
      url: "/python/overview_pcl.html"
    - title: 可與Ansible ONTAP
      url: "/automate/ontap_ansible.html"
    - title: 自動化部落格
      url: "/automate/blogs.html"
  - title: 更多資源
    links:
    - title: 取得更多資訊
      url: "/additional/get_more_information.html"
    - title: NetApp DevNet
      url: https://devnet.netapp.com/restapi.php
    - title: 9文件ONTAP
      url: https://docs.netapp.com/us-en/ontap/
    - title: 文件ONTAP Select
      url: https://docs.netapp.com/us-en/ontap-select/
product-family:
  name: ONTAP
  repo: ontap-family
  sidebar_label: 所有ONTAP 產品文件
