---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new features, new in release 
summary: NetApp會定期更新ONTAP Resrest API、為您帶來新功能、增強功能和錯誤修復。 
---
= 更新功能：利用靜止API與自動化技術ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp會定期更新ONTAP Resrest API、為您帶來新功能、增強功能和錯誤修復。


TIP: 您也應該檢閱 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["發行說明 ONTAP"^] 以取得其他資訊、包括已知的限制或問題。



== ONTAP 9.15.1.1

ONTAP 9.15.1 持續擴充 ONTAP REST API 的功能。此版本的更新相對較少、支援兩項新功能。

NFS over TLS:: 此功能有三個新端點可供使用。您可以發出這些 API 呼叫、以擷取所有透過 TLS 介面的 NFS 、以 UUID 擷取特定介面、以及更新 TLS 介面的組態內容。這些 API 呼叫總的來說是相當於的集合 `vserver nfs tls interface` CLI 命令。



CAUTION: 9.15.1 提供 ONTAP over TLS 的公開預覽功能。作為預覽產品、 ONTAP 9.15.1 的正式作業工作負載不支援此功能。

Windows 備份應用程式和 Unix 風格的符號連結:: 當 Windows 備份應用程式遇到 Unix 樣式的符號連結（ symlink ）時、連結會被遍歷、資料會由 ONTAP 傳回並備份。從 ONTAP 9.15.1 開始、您也可以選擇備份 symlink 、而非指向的資料。這可提供多項優點、包括改善備份應用程式的效能。端點 `/protocols/cifs/services/{svm.uuid}` 已更新、以將新參數納入 `backup-symlink-enabled` 物件中 `options` 。




== ONTAP 9.14.1.

ONTAP 9.14.1 版本包含超過三打的新 API 呼叫、可持續擴充 ONTAP REST API 的功能。這些端點支援多項新的 ONTAP 功能、以及現有功能的更新。此版本主要著重於安全性增強功能、但也包括 NAS 、 QoS 和效能指標的改善。

安全性:: ONTAP 9.14.1 推出兩項主要安全功能。開放式授權（ OAuth 2.0 ）是以權杖為基礎的架構、可用於限制對 ONTAP 儲存資源的存取。您可以將它與透過 REST API 存取 ONTAP 的用戶端搭配使用。您可以使用任何 ONTAP 管理介面（包括 REST API ）來執行組態。ONTAP 9.14.1 版本也支援 Cisco 雙核心、可為 SSH 登入提供雙因素驗證。您可以將雙核心設定為在 ONTAP 叢集或 SVM 層級上運作。除了這兩項新功能之外、我們也新增了數個端點、以改善對主要儲存區的控制。
FPolicy 持續儲存:: FPolicy 提供 ONTAP 原則管理平台。它為各種元件或元素（例如事件和原則引擎）提供容器。您現在可以使用 REST API 來設定和管理 ONTAP FPolicy 組態和事件的持續儲存區。每個 SVM 都可以有一個持續儲存區、供 SVM 中的多個原則共用。
QoS 選項:: 我們推出兩個端點、可讓您擷取及設定叢集的 QoS 選項。例如、您可以為背景工作保留一定百分比的可用系統處理資源。
效能指標:: ONTAP 會維護系統操作特性的統計資訊。此資訊以由表格和資料列組成的資料庫格式呈現。使用 ONTAP 9.14.1 時、會在數個資源類別中新增額外的度量資料、包括光纖通道、 iSCSI 、 LUN 和 NVMe 。這項額外的度量資料持續使 ONTAP REST API 與 Data ONTAP API （ ONTAPI 或 ZAPI ）接近同位。
其他增強功能:: 視您的環境而定、還有幾項額外的增強功能可能會有所幫助。這些新端點可改善對 SAN 啟動器的存取、控制主機快取設定、並可存取個別的 AutoSupport 訊息。




== ONTAP 9.13.1.12.9.11.9.11.

ONTAP 9.13.1 透過超過二十個新的 API 呼叫、持續擴充 ONTAP REST API 的功能。這些端點支援ONTAP 全新的功能、以及現有功能的增強功能。此版本著重於安全性、資源管理、增強的 SVM 組態選項和效能指標等方面的改善。

資源標記:: 您可以使用標記將 REST API 資源分組。您可以這樣做、將特定專案或組織群組中的相關資源建立關聯。使用標記有助於更有效地組織及追蹤資源。
一致性群組:: ONTAP 9.13.1 持續擴大效能計數器資料的可用度。您現在可以存取這類統計資訊、以追蹤一致性群組的歷史效能和容量。此外、我們也加入了增強功能、可設定及管理一致性群組之間的父子關係。
每個 SVM 的 DNS 組態:: 現有的 DNS 端點已擴充、可讓個別 SVM 執行 DNS 網域和伺服器組態。
EMS 角色組態:: 現有的 EMS 支援功能已擴充、可管理角色、以及指派給角色的存取控制組態。這可根據角色組態來限制或篩選事件和訊息。
安全性:: 您可以使用 REST API 為使用 SSH 登入和存取 ONTAP 的帳戶設定時間型一次性密碼（ TOTP ）設定檔。此外、金鑰管理程式端點也已擴充、可從指定的金鑰管理伺服器提供還原作業。
每個 SVM 的 CIFS 組態:: 現有的 CIFS 端點已擴充、可更新特定 SVM 的組態。
S3 貯體規則:: 現有的 S3 儲存區端點已擴充、納入規則定義。每個規則都是清單物件、並定義要在貯體內物件上執行的一組動作。這些規則可讓您更有效地管理 S3 儲存區的生命週期。




== 零點9.12.1. ONTAP

藉由40多個新的API呼叫、更新版的功能將不斷擴充。ONTAP ONTAP這些端點支援ONTAP 全新的功能、以及現有功能的增強功能。本版本著重於安全性與NAS功能的改善。

安全性增強功能:: Amazon Web Services包含金鑰管理服務、可為金鑰和其他機密提供安全的儲存。您可以透過REST API存取此服務、以便ONTAP 讓效益分析能夠將加密金鑰安全地儲存在雲端。此外、您也可以建立及列出與NetApp儲存加密搭配使用的驗證金鑰。
Active Directory:: 您可以管理針對ONTAP 某個叢集定義的Active Directory帳戶。這包括建立新帳戶、以及顯示、更新及刪除帳戶。
CIFS群組原則:: REST API已經過增強、可支援CIFS群組原則的建立與管理。組態資訊可透過套用至所有或特定SVM的群組原則物件來使用和管理。




== 零點9.11.1. ONTAP

藉由將近一百個新的API呼叫、即可繼續擴充《無線更新API》的功能。ONTAP ONTAP這些端點支援全新ONTAP 的功能、以及現有功能的增強功能。此版本著重於支援客戶從ONTAP 無法支援的API（Data ONTAP ONTAPI或ZAPI）移轉至R靜止API。

精細RBAC:: 以角色為基礎的存取控制（RBAC）功能已經過強化、可提供更精細的資料。ONTAP您可以使用傳統角色、或透過REST API視需要建立新的自訂角色。每個角色都與一個或多個權限相關聯、每個權限都會識別REST API呼叫或CLI命令以及存取層級。REST 角色可以使用新的存取層級、例如 `read_create` 和 `read_modify`。這項增強功能可提供Data ONTAP 與靜態API（ONTAPI或ZAPI）的同位元、並支援客戶移轉至REST API。請參閱 link:rest/rbac_overview.html["RBAC安全性"] 以取得更多資訊。
效能計數器:: 先前ONTAP 發行的版本保留了系統運作特性的統計資訊。9.11.1版已增強此資訊、現在可透過REST API取得。系統管理員或自動化程序可以存取資料、以判斷系統效能。統計資訊由計數器管理子系統維護、以資料庫格式顯示、並使用表格和列。這項增強功能可ONTAP 讓靜態API更接近Data ONTAP 於使用靜態API（ONTAPI或ZAPI）。
Aggregate管理:: 加強了對不經改良的儲存集合體的管理ONTAP 。您可以使用更新的REST端點、將Aggregate移至線上和離線狀態、以及管理備援磁碟機。
IP子網路功能:: 此功能已擴充為支援IP子網路。ONTAPREST API可讓您存取ONTAP 組態設定、並管理一個叢集內的IP子網路。
多重系統管理員驗證:: 多重管理員驗證功能提供靈活的授權架構、可保護ONTAP 對各種指令或作業的存取。您可以定義用來識別受限命令的規則。當使用者要求存取特定命令時、可ONTAP 視情況由多位元管理員授予核准。
SnapMirror增強功能:: SnapMirror功能已在多個領域（包括排程）中獲得增強。在DP關係中加入了與Rz9.11.1的靜態關係同位元檢查、而REST API提供的節流功能已達到與RzAPI（ONTAPI或ZAPI）的同位元檢查。SnapVault ONTAP Data ONTAP與此相關、我們提供支援來建立及管理大量Snapshot複本。
儲存資源池:: 我們新增了多個端點、以便存取ONTAP 功能豐富的功能。支援建立及列出叢集中的儲存資源池、以及依ID更新及刪除特定資源池。
名稱服務快取支援:: 支援快取功能的支援功能已增強了名稱服務、可提升效能與恢復能力。ONTAP名稱服務快取的組態現在可透過REST API存取。可在多個層級套用設定、包括：主機、UNIX使用者、UNIX群組和網路群組。
ONTAPI報告工具:: ONTAPI報告工具可協助客戶和合作夥伴識別其環境中的ONTAPI使用量。除了Python軟體之外、NetApp隨選實驗室也提供影片和不斷演進的支援。此工具可在從ONTAPI移轉至ONTAP REST API時提供另一項資源。




== 零點9.10.1 ONTAP

而供應的功能也不斷擴大。ONTAP ONTAP我們新增了超過一百個新的端點、以支援ONTAP 全新的功能、以及對現有功能的增強功能。其餘API增強功能的摘要如下所示。

應用程式一致性群組:: 一致性群組是一組磁碟區、在執行某些作業（例如快照）時、會將這些磁碟區群組在一起。此功能可在一組磁碟區中執行單一磁碟區作業、藉此延伸相同的損毀一致性和資料完整性。對於大型的多Volume工作負載應用程式而言、這項功能非常重要。
SVM移轉:: 您可以將SVM從來源叢集移轉至目的地叢集。新的端點提供完整的控制、包括暫停、恢復、擷取狀態及中止移轉作業的功能。
檔案複製與管理:: Volume層級的檔案複製與管理功能已增強。新的REST端點支援檔案移動、複製及分割作業。
改善S3稽核:: 稽核S3事件是一項安全性改善、可讓您追蹤及記錄特定S3事件。S3稽核事件選取器可依每個SVM設定為每個儲存區。
勒索軟體防禦:: 可偵測可能含有勒索軟體威脅的檔案。ONTAP您可以擷取這些可疑檔案的清單、並將其從磁碟區中移除。
其他安全性增強功能:: 有幾項一般的安全性增強功能可擴充現有的傳輸協定並引進新功能。IPsec、金鑰管理、SSH組態和檔案權限等方面已有改善。
CIFS網域和本機群組:: 叢集與SVM層級已新增CIFS網域支援。您可以擷取網域組態、以及建立和移除慣用的網域控制器。
擴充Volume分析:: Volume分析和指標已透過其他端點進行擴充、以支援熱門檔案、目錄和使用者。
支援增強功能:: 多項新功能增強了支援。自動更新ONTAP 功能可下載並套用最新的軟體更新、讓您的更新版不中斷。您也可以擷取及管理節點產生的記憶體核心傾印。




== 部分9.9.1 ONTAP

而供應器的功能也不斷擴充、ONTAP ONTAP有新的API端點可用於現有ONTAP 的功能、包括SAN連接埠集和Vserver檔案目錄安全性。此外、我們也新增了端點、以支援ONTAP 全新的功能與增強功能。相關文件也有所改善。以下為增強功能的摘要。

將ONTAPI對應至ONTAP Rest 9 API:: 為了協助您將ONTAP 自己的自動化程式碼轉換為REST API、NetApp提供API對應文件。此參考包含每個的ONTAPI呼叫清單和REST API等效值。地圖文件已更新、加入全新ONTAP 的《更新版》、以涵蓋全新的《更新版》、《更新版》。請參閱 link:migrate/mapping.html["用於REST API對應的ONTAPI"] 以取得更多資訊。
API端點提供ONTAP 全新的功能、以利更新的功能:: REST API已新增對ONTAP 無法透過ONTAPI API取得的全新功能的支援功能。這包括支援巢狀igroup和Google Cloud Key Management Services。
改善從ONTAPI移轉至REST的支援:: 更多舊版ONTAPI呼叫現在具有對應的REST API等效項目。這包括本機Unix使用者和群組、不需用戶端、SAN連接埠集和磁碟區空間屬性、即可管理NTFS檔案安全性。這些變更也包含在更新的ONTAPI中、以供REST對應文件使用。
增強的線上文件:: 目前、《支援》線上文件參考頁面上的標籤會指出推出每個REST端點或參數時的發行版、包括採用《支援》更新版本的更新版本。ONTAP ONTAP ONTAP




== 部分9.8 ONTAP

由於資料豐富、因此可大幅擴充不景API的廣度和深度。ONTAP ONTAP其中包含多項新功能、可提升您自動化ONTAP 部署及管理功能的能力。此外、支援也已改善、可協助從舊版ONTAPI移轉至REST。

將ONTAPI對應至ONTAP Rest 9 API:: 為了協助您更新ONTAPI自動化、NetApp提供一組需要一或多個輸入參數的ONTAPI呼叫清單、以及將這些呼叫對應到等效ONTAP 的等效的等效的等效的等效的等效的等效的等效的等效的等效的等效的等效的等效指令API呼叫。請參閱 link:migrate/mapping.html["用於REST API對應的ONTAPI"] 以取得更多資訊。
API端點提供ONTAP 全新的功能、以利實現全新的功能:: REST API已新增對ONTAP 新核心的支援、無法透過ONTAPI取得這些功能。這包括支援ONTAP REST API以支援SS3儲存區和服務、SnapMirror營運不中斷和檔案系統分析。
擴充支援以增強安全性:: 透過支援多種服務與傳輸協定、包括Azure Key Vault、Google Cloud Key Management Services、IPSec及憑證簽署要求、安全性已獲得增強。
提升簡易性的增強功能:: 利用REST API、提供更有效率且更現代化的工作流程。ONTAP例如、OneClick韌體更新現已可供多種不同類型的韌體使用。
增強的線上文件:: 現在、「樣版」文件頁面上有標籤、指出推出的每個REST端點或參數的版本均為「樣版」、包括9.8版的新增標籤。ONTAP ONTAP
改善從ONTAPI移轉至REST的支援:: 現在更多的舊版ONTAPI呼叫具有對應的REST API等效項目。此外、我們也提供文件來協助識別應使用哪個REST端點來取代現有的ONTAPI呼叫。
擴充效能指標:: REST API的效能指標已經過擴充、包括數個新的儲存設備和網路物件。




== 更新ONTAP

藉由引進三種新的資源類別、每種資源類別都有多個REST端點、藉此延伸出R靜止API的功能範圍：ONTAP ONTAP

* NDMP
* 物件存放區
* SnapLock


此外、還在多個現有資源類別中引進一或多個新的REST端點：ONTAP

* 叢集
* NAS
* 網路
* NVMe
* SAN
* 安全性
* 儲存設備
* 支援




== 部分9.6 ONTAP

支援原創於支援的REST API、可大幅延伸至支援的32個部分。ONTAP ONTAP支援大部分的靜態組態和管理工作的不支援使用支援。ONTAP ONTAP

REST API在ONTAP 32：9.6中包含下列關鍵領域及更多內容：

* 叢集設定
* 傳輸協定組態
* 資源配置
* 效能監控
* 資料保護
* 應用程式感知資料管理

