---
sidebar: sidebar 
permalink: resources/cluster.html 
keywords: cluster resources 
summary: 您可以使用這些API呼叫來管理ONTAP 支援的叢集和相關資源。 
---
= ONTAP REST API 中的叢集資源
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用這些API呼叫來管理ONTAP 支援的叢集和相關資源。

.容量資源池
容量集區授權模式可讓您從共用集區為每個叢集節點授權儲存容量。此資源類型是ONTAP 更新的功能、採用了更新的功能。

.機箱
機箱是支援叢集的硬體架構。此資源類型隨ONTAP 附於NetApp 9.6。

.叢集
一個由一個或多個節點組成的叢集、以及定義儲存系統的相關組態設定。ONTAP此資源類型隨ONTAP 附於NetApp 9.6。

.計數器表
Counter Manager子系統會擷取各種有關的統計資訊ONTAP 。您可以存取此資訊來評估系統效能。此資源類型隨ONTAP 附於引用的功能。9.11

.韌體
您可以擷取韌體更新要求的歷程記錄。此資源類型是ONTAP 更新的功能、採用了更新的功能。

.工作
非同步REST API要求是使用工作鎖定的背景工作來執行。此資源類型隨ONTAP 附於NetApp 9.6。

.授權執行個體
每個授權均可以個別套件的形式進行管理。此資源類型隨ONTAP 附於NetApp 9.6。

.授權管理員
您可以管理與ONTAP 某個叢集相關之每個授權管理程式執行個體的組態和其他相關資訊。此資源類型是ONTAP 更新的功能、採用了更新的功能。

.授權
授權可讓您實作特定ONTAP 的功能。此資源類型隨ONTAP 附於NetApp 9.6。

.中介 ping
您可以 ping 通BlueXP雲端服務。此資源類型是ONTAP 9.17.1 中的新增資源類型。

.協調員
您可以管理與MetroCluster關聯的調解器，包括新增或刪除調解器實例。此資源類型是ONTAP 9.8 中的新增資源類型，並在 9.17.1 中進行了更新。

.MetroCluster
您可以建立及管理MetroCluster 一套功能豐富的部署、包括執行切換或切換作業。此資源類型為ONTAP 更新版本、更新版本為9.11、更新版本為更新版本9.8。

.診斷MetroCluster
您可以對MetroCluster 整個部署執行診斷作業、並擷取結果。此資源類型是ONTAP 更新的功能、採用了更新的功能。

.解決災難恢復群組MetroCluster
您可以執行MetroCluster 與「不中斷災難恢復」群組相關的作業。此資源類型是ONTAP 更新的功能、採用了更新的功能。

.資訊互連MetroCluster
您可以擷取MetroCluster 「不互通」狀態。此資源類型是ONTAP 更新的功能、採用了更新的功能。

.節點MetroCluster
您可以在MetroCluster 一套功能性的部署中擷取個別節點的狀態。此資源類型是ONTAP 更新的功能、採用了更新的功能。

.營運MetroCluster
您可以擷取最近執行的作業清單、以利MetroCluster 執行某個版本的功能。此資源類型是ONTAP 更新的功能、採用了更新的功能。

.SVM MetroCluster
您可以擷取MetroCluster 有關整個SVM配對的資訊、以供參考。此資源類型隨ONTAP 附於引用的功能不只是功能。9.11.1。

.節點
由一或多個節點組成的叢集。ONTAP此資源類型採用ONTAP 了更新ONTAP 版本的32個版本、更新版本為32個版本。

.NTP金鑰
網路時間傳輸協定（NTP）可設定為使用ONTAP 共享的私密金鑰、在受到信任的外部NTP時間伺服器之間使用。此資源類型隨ONTAP 附於NetApp 9.7。

.NTP伺服器
您可以使用這些API呼叫來設定ONTAP 「靜態網路時間傳輸協定」設定、包括外部NTP伺服器和金鑰。此資源類型隨ONTAP 附於NetApp 9.7。

.對等端點
對等物件代表端點、並支援叢集對等關係。此資源類型隨ONTAP 附於NetApp 9.6。

.效能計數器
先前ONTAP 發行的版本保留了系統運作特性的統計資訊。隨著9.11.1版本的推出、資訊已經過強化、現在可透過REST API取得。此功能可ONTAP 讓RureREST API更接近Data ONTAP 於使用該API（ONTAPI或ZAPI）的同位元。此資源類型隨ONTAP 附於引用的功能。9.11

.資源標籤
您可以使用標記將 REST API 資源分組。您可以這樣做、將特定專案或組織群組中的相關資源建立關聯。使用標記有助於更有效地組織及追蹤資源。ONTAP 9.13 引進了這種資源類型。

.排程
排程可用於自動化工作的執行。此資源類型隨ONTAP 附於NetApp 9.6。

.感測器
您可以使用這些端點來擷取所有平台環境感測器的詳細資料。此資源類型隨ONTAP 附於引用的功能。9.11

.軟體
一個包含叢集軟體設定檔、軟體套件集合、以及軟體歷史記錄的叢集。ONTAP此資源類型採用ONTAP 了更新ONTAP 版本的32個版本、更新版本為32個版本。

.網路
您可以使用這些端點來更新Web服務組態、以及擷取目前的組態。此資源類型隨ONTAP 附於引用的功能不只是功能。9.10。
