---
sidebar: sidebar 
permalink: resources/san.html 
keywords: san resources 
summary: 您可以使用這些API呼叫來管理SAN資源。 
---
= SAN
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用這些API呼叫來管理儲存區域網路（SAN）資源。

.Fibre Channel登入
Fibre Channel登入代表光纖通道啟動器所建立的連線、這些啟動器已登入ONTAP 到了功能鏈路。此資源類型隨ONTAP 附於NetApp 9.6。

.Fibre Channel Protocol服務
光纖通道傳輸協定（FCP）服務可定義SVM的光纖通道目標內容。此資源類型採用ONTAP 了更新ONTAP 版的32個版本、更新版為32個版本。

.Fibre Channel WWPN別名
全球連接埠名稱（WWPN）是唯一識別光纖通道連接埠的64位元值。此資源類型隨ONTAP 附於NetApp 9.6。

.igroup
啟動器群組（igroup）是光纖通道WWPN（全球連接埠名稱）、iSCSI IQN（合格名稱）和iSCSI EUI（延伸唯一識別碼）的集合、可識別主機啟動器。這種資源類型最初是以ONTAP 引用功能不適用的功能為設計目標。

巢狀igroup是ONTAP 功能更新的功能、包含了更新版的支援功能、REST API也加入了支援功能。此REST資源類型隨ONTAP 附於引用的地方。9.9

.iSCSI認證
iSCSI認證物件包含啟動器和ONTAP 物件所使用的驗證認證資料。此資源類型隨ONTAP 附於NetApp 9.6。

.iSCSI服務
iSCSI服務可定義SVM的iSCSI目標內容。此資源類型採用ONTAP 了更新ONTAP 版的32個版本、更新版為32個版本。

.iSCSI工作階段
iSCSI工作階段是一或多個TCP連線、可將iSCSI啟動器與iSCSI目標連結。此資源類型隨ONTAP 附於NetApp 9.6。

.LUN屬性
LUN屬性是呼叫者定義的名稱/值配對、可選擇性地與LUN一起儲存。屬性可用來儲存少量的應用程式專屬中繼資料、ONTAP 而不被支援。端點可讓您建立、更新、刪除及探索LUN的屬性。此資源類型隨ONTAP 附於引用的功能不只是功能。9.10。

.LUN對應
LUN對應是LUN與啟動器群組之間的關聯。此資源類型隨ONTAP 附於NetApp 9.6。

.LUN對應報告節點
報告節點是叢集節點、可透過SAN傳輸協定、將連至對應LUN的網路路徑做為ONTAP 供應器的選擇性LUN對應（SLE）功能的一部分、進行通告。新的端點可讓您新增、移除及探索LUN對應的報告節點。此資源類型隨ONTAP 附於引用的功能不只是功能。9.10。

.LUN
LUN是儲存區域網路（SAN）中儲存設備的邏輯代表。此資源類型採用ONTAP 了更新ONTAP 版的32個版本、更新版為32個版本。

.連接埠集
連接埠集是與_portSet_ Storage VM相關聯的光纖通道或iSCSI網路介面的集合。雖然ONTAP 此功能已存在於先前版本的支援、但其餘API現在已加入支援。此REST資源類型隨ONTAP 附於引用的地方。9.9

.VVOL繫結
VMware虛擬磁碟區（vVol）繫結是指類「傳輸協定端點」的LUN與類「VVOL」的LUN之間的關聯。vVol繫結REST API可讓您建立、刪除及探索vVol繫結。此資源類型隨ONTAP 附於引用的功能不只是功能。9.10。
