---
sidebar: sidebar 
permalink: resources/security.html 
keywords: rest, rest api, security, security resources 
summary: 您可以使用這些 API 呼叫來管理叢集和 SVM 的安全性設定。 
---
= ONTAP REST API 中的安全資源
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用這些 API 呼叫來管理叢集和 SVM 的安全性設定。

.帳戶
叢集和SVM的使用者帳戶集合。此資源類型隨ONTAP 附於NetApp 9.6。

.帳戶名稱
範圍內使用者帳戶的組態。此資源類型隨ONTAP 附於NetApp 9.6。

.Active Directory Proxy
您可以在Active Directory伺服器上管理SVM帳戶資訊。此資源類型隨ONTAP 附於NetApp 9.7。

.反勒索軟體
可偵測可能含有勒索軟體威脅的檔案。ONTAP端點有數種類別。您可以擷取這些可疑檔案的清單、並將其從磁碟區中移除。此資源類型隨ONTAP 附於引用的功能不只是功能。9.10.1。ONTAP 9 新增了顯示版本及更新反勒索軟體套件的支援。 16

.反勒索軟體熵統計
針對自主勒索軟體防護 (ARP) 功能的運行，提供了詳細的熵統計資訊。此資源類型已在ONTAP 9.17.1 中新增。

.稽核
決定稽核記錄檔記錄內容的設定。此資源類型隨ONTAP 附於NetApp 9.6。

.稽核目的地
這些設定可控制稽核記錄資訊如何轉送到遠端系統或Splunk伺服器。此資源類型隨ONTAP 附於NetApp 9.6。

.稽核訊息
您可以擷取稽核記錄訊息。此資源類型隨ONTAP 附於NetApp 9.6。

.AWS KMS
Amazon Web Services包含金鑰管理服務、可為金鑰和其他機密提供安全的儲存。您可以透過REST API存取此服務、以便ONTAP 讓效益分析能夠將加密金鑰安全地儲存在雲端。此外、您也可以建立及列出與NetApp儲存加密搭配使用的驗證金鑰。此支援功能是ONTAP 更新的功能、採用了更新版的支援功能。

.Azure Key Vault
這組API呼叫可讓您使用Azure Key Vault來儲存ONTAP 功能完善的加密金鑰。此資源類型是ONTAP 更新的功能、採用了更新的功能。

.巴比肯 KMS
已新增對 OpenStack Barbican 金鑰管理器的支持，以維護NetApp磁碟區加密 (NVE) 的金鑰。此資源類型已在ONTAP 9.17.1 中新增。

.憑證
API呼叫可用於安裝、顯示ONTAP 及刪除由資訊技術所使用的憑證。此資源類型隨ONTAP 附於NetApp 9.7。

.Cisco DuoTM
雙核心為 SSH 登入提供雙因素驗證。您可以將雙核心設定為在 ONTAP 叢集或 SVM 層級上運作。ONTAP 9.14 引進了這種資源類型。

.叢集安全性
您可以擷取整個叢集的安全性詳細資料、並更新某些參數。此資源類型是以ONTAP 更新ONTAP 版本的更新版本介紹、並以更新版本的更新版本為更新版本。

.外部角色
外部角色是在 OAuth 2.0 識別提供者定義。您可以建立及管理這些外部角色與 ONTAP 角色之間的對應關係。ONTAP 9.16 引進了這種資源類型。

.GCP KMS
這組API呼叫可讓您使用Google Cloud Platform Key Management Service來儲存及管理ONTAP 此等加密金鑰。這種資源類型最初是以ONTAP 《不只是用作參考資料的參考資料9、8、8、9、8不過ONTAP 、這項功能已重新設計、因此在更新資源類型時、將會被視為全新功能、如更新於本文件中的9.9。

.群組
您可以管理群組組組態，包括以 UUID 表示的群組。ONTAP 9.16 引進了這種資源類型。

.群組角色對應
您可以建立及管理群組與角色之間的對應關係。ONTAP 9.16 引進了這種資源類型。

.IPsec
網際網路傳輸協定安全性（IPSec）是一套傳輸協定、可在基礎IP網路上的兩個端點之間提供安全性。此資源類型是ONTAP 更新的功能、採用了更新的功能。

.IPsec CA憑證
您可以新增、移除及擷取IPSec CA憑證。此資源類型是ONTAP 更新的、採用了更新版的功能。

.IPsec原則
您可以使用這組API呼叫來管理適用於IPSec部署的原則。此資源類型是ONTAP 更新的功能、採用了更新的功能。

.IPsec安全關聯
您可以使用這組API呼叫來管理在進行IPSec部署時有效的安全關聯。此資源類型是ONTAP 更新的功能、採用了更新的功能。

.即時 (JIT) 權限提升
(JIT) 權限提升是對基於角色的存取控制 (RBAC) 的增強。叢集管理員可以請求臨時提升到現有角色。此資源類型已在ONTAP 9.17.1 中新增。

.關鍵管理程式組態
這些端點可讓您擷取及更新金鑰管理程式的組態。此資源類型是ONTAP 更新的、採用了更新版的功能。

.關鍵經理
金鑰管理程式可讓ONTAP 支援的用戶端模組安全地儲存金鑰。此資源類型採用ONTAP 了更新ONTAP 版本的32、6、6、9、6、9、6、5、6、5、5另一項ONTAP 更新以支援驗證金鑰。ONTAP 9.13 新增了還原功能。

.主要儲存區
金鑰庫說明金鑰管理程式的類型。此資源類型是ONTAP 更新的、採用了更新版的功能。ONTAP 9.14 新增了其他支援增強控制的端點。

.LDAP驗證
這些API呼叫是用來擷取及管理叢集LDAP伺服器組態。此資源類型隨ONTAP 附於NetApp 9.6。

.登入訊息
用於顯示及管理ONTAP 由資訊技術所使用的登入訊息。此資源類型隨ONTAP 附於NetApp 9.6。

.多重系統管理員驗證
多重管理員驗證功能提供靈活的授權架構、可保護ONTAP 對各種指令或作業的存取。有17個新的端點支援定義、要求及核准下列領域的存取：

* 規則
* 要求
* 核准群組


提供多位管理員核准存取的選項、可提升ONTAP 您的支援和IT環境的安全性。這些資源類型是ONTAP 以引用的功能為參考9.11。

.NIS驗證
這些設定可用來擷取及管理叢集NIS伺服器組態。此資源類型隨ONTAP 附於NetApp 9.6。

.OAuth 2.0
開放式授權（ OAuth 2.0 ）是以權杖為基礎的架構、可用於限制對 ONTAP 儲存資源的存取。您可以將它與透過 REST API 存取 ONTAP 的用戶端搭配使用。ONTAP 9.14 引進了這種資源類型。ONTAP 9 第 16 節透過支援 Microsoft Entra ID 授權伺服器（前身為 Azure AD ）的標準 OAUTH 2.0 宣告來增強此功能。此外，新的群組和角色對應功能也支援以 UUID 樣式值為基礎的 Entra ID 標準群組宣告。此外，我們也推出新的外部角色對應功能。另請參閱 * 外部角色 * ， * 群組 * 及 * 群組角色對應 * 。

.密碼驗證
這包括用來變更使用者帳戶密碼的API呼叫。此資源類型隨ONTAP 附於NetApp 9.6。

.角色執行個體的權限
管理特定角色的權限。此資源類型隨ONTAP 附於NetApp 9.6。

.公開金鑰驗證
您可以使用這些API呼叫來設定使用者帳戶的公開金鑰。此資源類型隨ONTAP 附於NetApp 9.7。

.角色
這些角色可讓您將權限指派給使用者帳戶。此資源類型隨ONTAP 附於NetApp 9.6。

.角色執行個體
角色的特定執行個體。此資源類型隨ONTAP 附於NetApp 9.6。

.SAML服務供應商
您可以顯示及管理SAML服務供應商的組態。此資源類型隨ONTAP 附於NetApp 9.6。

.SAML 服務提供者預設元數據
您可以管理叢集的 SAML 預設元資料配置。此資源類型是在ONTAP 9.17.1 中新增的。

.SSH
這些呼叫可讓您設定SSH組態。此資源類型隨ONTAP 附於NetApp 9.7。

.SSH SVM
這些端點可讓您擷取所有SVM的SSH安全組態。此資源類型隨ONTAP 附於引用的功能不只是功能。9.10。

.TOTPS
您可以使用 REST API 為使用 SSH 登入和存取 ONTAP 的帳戶設定時間型一次性密碼（ TOTP ）設定檔。ONTAP 9.13 引進了這種資源類型。

.網路驗證
Web 驗證（ WebAuthn ）是一種網路標準，可根據公開金鑰密碼編譯來安全地驗證使用者。有了 ONTAP ，它就能透過系統管理員和 ONTAP REST API 來支援管理網路釣魚的一致性 MFAs 。此功能已隨 ONTAP 9 16 一起新增。
