---
sidebar: sidebar 
permalink: resources/security.html 
keywords:  
summary:  
---
= 安全性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
這些API呼叫可用於管理叢集和SVM安全性設定。



==== 帳戶

叢集和SVM的使用者帳戶集合。此資源類型隨ONTAP 附於NetApp 9.6。



==== 帳戶名稱

範圍內使用者帳戶的組態。此資源類型隨ONTAP 附於NetApp 9.6。



==== Active Directory Proxy

您可以在Active Directory伺服器上管理SVM帳戶資訊。此資源類型隨ONTAP 附於NetApp 9.7。



==== 反勒索軟體

可偵測可能含有勒索軟體威脅的檔案。ONTAP端點有數種類別。您可以擷取這些可疑檔案的清單、並將其從磁碟區中移除。此資源類型隨ONTAP 附於引用的功能為NetApp資源9.10.1。



==== 稽核

決定稽核記錄檔記錄內容的設定。此資源類型隨ONTAP 附於NetApp 9.6。



==== 稽核目的地

這些設定可控制稽核記錄資訊如何轉送到遠端系統或Splunk伺服器。此資源類型隨ONTAP 附於NetApp 9.6。



==== 稽核訊息

您可以擷取稽核記錄訊息。此資源類型隨ONTAP 附於NetApp 9.6。



==== AWS KMS

這組API呼叫可讓您使用Amazon Web Services Key Management Service來儲存ONTAP 此等加密金鑰。此資源類型是ONTAP 更新的功能、採用了更新的功能。



==== Azure Key Vault

這組API呼叫可讓您使用Azure Key Vault來儲存ONTAP 功能完善的加密金鑰。此資源類型是ONTAP 更新的功能、採用了更新的功能。



==== 憑證

API呼叫可用於安裝、顯示ONTAP 及刪除由資訊技術所使用的憑證。此資源類型隨ONTAP 附於NetApp 9.7。



==== 叢集安全性

您可以擷取整個叢集的安全性詳細資料、並更新某些參數。此資源類型是以ONTAP 更新ONTAP 版本的更新版本介紹、並以更新版本的更新版本為更新版本。



==== GCP KMS

這組API呼叫可讓您使用Google Cloud Platform Key Management Service來儲存及管理ONTAP 此等加密金鑰。這種資源類型最初是以ONTAP 《不只是用作參考資料的參考資料9、8、8、9、8不過ONTAP 、這項功能已重新設計、因此在更新資源類型時、將會被視為全新功能、如更新於本文件中的9.9。



==== IPsec

網際網路傳輸協定安全性（IPSec）是一套傳輸協定、可在基礎IP網路上的兩個端點之間提供安全性。此資源類型是ONTAP 更新的功能、採用了更新的功能。



==== IPsec CA憑證

您可以新增、移除及擷取IPSec CA憑證。此資源類型是ONTAP 更新的、採用了更新版的功能。



==== IPsec原則

您可以使用這組API呼叫來管理適用於IPSec部署的原則。此資源類型是ONTAP 更新的功能、採用了更新的功能。



==== IPsec安全關聯

您可以使用這組API呼叫來管理在進行IPSec部署時有效的安全關聯。此資源類型是ONTAP 更新的功能、採用了更新的功能。



==== 關鍵管理程式組態

這些端點可讓您擷取及更新金鑰管理程式的組態。此資源類型是ONTAP 更新的、採用了更新版的功能。



==== 關鍵經理

金鑰管理程式可讓ONTAP 支援的用戶端模組安全地儲存金鑰。此資源類型採用ONTAP 了更新ONTAP 版本的32、6、6、9、6、9、6、5、6、5、5



==== 主要儲存區

金鑰庫說明金鑰管理程式的類型。此資源類型是ONTAP 更新的、採用了更新版的功能。



==== LDAP驗證

這些API呼叫是用來擷取及管理叢集LDAP伺服器組態。此資源類型隨ONTAP 附於NetApp 9.6。



==== 登入訊息

用於顯示及管理ONTAP 由資訊技術所使用的登入訊息。此資源類型隨ONTAP 附於NetApp 9.6。



==== 多重系統管理員驗證

多重管理員驗證功能提供靈活的授權架構、可保護ONTAP 對各種指令或作業的存取。有17個新的端點支援定義、要求及核准下列領域的存取：

* 規則
* 要求
* 核准群組


提供多位管理員核准存取的選項、可提升ONTAP 您的支援和IT環境的安全性。這些資源類型均隨ONTAP 附於引用資料的功能。



==== NIS驗證

這些設定可用來擷取及管理叢集NIS伺服器組態。此資源類型隨ONTAP 附於NetApp 9.6。



==== 密碼驗證

這包括用來變更使用者帳戶密碼的API呼叫。此資源類型隨ONTAP 附於NetApp 9.6。



==== 角色執行個體的權限

管理特定角色的權限。此資源類型隨ONTAP 附於NetApp 9.6。



==== 公開金鑰驗證

您可以使用這些API呼叫來設定使用者帳戶的公開金鑰。此資源類型隨ONTAP 附於NetApp 9.7。



==== 角色

這些角色可讓您將權限指派給使用者帳戶。此資源類型隨ONTAP 附於NetApp 9.6。



==== 角色執行個體

角色的特定執行個體。此資源類型隨ONTAP 附於NetApp 9.6。



==== SAML服務供應商

您可以顯示及管理SAML服務供應商的組態。此資源類型隨ONTAP 附於NetApp 9.6。



==== SSH

這些呼叫可讓您設定SSH組態。此資源類型隨ONTAP 附於NetApp 9.7。



==== SSH SVM

這些端點可讓您擷取所有SVM的SSH安全組態。此資源類型隨ONTAP 附於引用的功能不只是功能。9.10。
