---
sidebar: sidebar 
permalink: resources/storage.html 
keywords: storage resources 
summary: 您可以使用這些API呼叫來管理實體和邏輯儲存設備。 
---
= ONTAP REST API 中的儲存資源
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用這些API呼叫來管理實體和邏輯儲存設備。

.Aggregate度量
您可以擷取特定Aggregate的歷史度量資料。此資源類型採用ONTAP 了更新ONTAP 版的32個版本、更新版為32個版本。

.Aggregate plexes
集合體內的實體版的實體版次。WAFL此資源類型隨ONTAP 附於NetApp 9.6。

.集合體
集合體由一或多個RAID群組組成。此資源類型隨ONTAP 附於NetApp 9.6。

.橋接器
您可以擷取叢集中的橋接器。此資源類型隨ONTAP 附於引用的資料檔9.9。

.磁碟
叢集中的實體磁碟。此資源類型採用ONTAP 了更新ONTAP 版本的32個版本、更新版本為32個版本、更新版本為32個版本。

.檔案複製
您可以使用這些端點來建立檔案複製、擷取分割狀態、以及管理分割負載。檔案複製端點資源是ONTAP 以支援還原9.6的方式推出、並以ONTAP 支援還原9.8的方式擴充。他們再次以ONTAP 版本9.10大幅擴充。

.檔案搬移
您可以使用這些REST API端點、在兩FlexVol 個REST Volume之間或FlexGroup 在一個靜態Volume內移動檔案。接受申請後、您可以監控進度和狀態。此資源類型隨ONTAP 附於引用的功能不只是功能。9.11.1。

.FlexCache
此資源類型採用ONTAP 了更新ONTAP 版本的32個版本、更新版本為32個版本。

.FlexCache連線狀態
您可以取得FlexCache連線狀態。此資源類型是在ONTAP 9.18 中引入的。

.來源FlexCache
不只是來源磁碟區的持續快取、FlexCache這種資源類型最初是以ONTAP 引用功能不適用的功能為設計目標。支援功能已透過ONTAP 支援透過HTTP修補方法進行的更新、以支援更新。

.受監控的檔案
您可以指定特定檔案以進行其他監控。此資源類型是ONTAP 更新的功能、採用了更新的功能。

.資源池
您可以建立共用儲存資源池、並擷取叢集中的儲存資源池。此資源類型隨ONTAP 附於引用的功能不只是功能。9.11.1。

.連接埠
叢集的儲存連接埠。此資源類型採用ONTAP 了NetApp 9.6技術、ONTAP 並以NetApp 9.11.1技術強化。

.QoS原則
服務品質原則組態。此資源類型隨ONTAP 附於NetApp 9.6。

.QoS 選項
我們已推出端點、可讓您擷取及設定叢集的 QoS 選項。例如、您可以為背景工作保留一定百分比的可用系統處理資源。ONTAP 9.14 引進了這種資源類型。

.QoS工作負載
QoS工作負載代表QoS追蹤的儲存物件。您可以擷取QoS工作流程。此資源類型隨ONTAP 附於引用的功能不只是功能。9.10。

.qtree
您可以使用這些API呼叫來管理qtree、這是一種邏輯分隔的檔案系統。ONTAP 9.6 引進了這種資源類型。qtree 延伸效能監控功能已新增至 ONTAP 9 。 16.1 。

.配額報告
報告配額、這是一種限制或追蹤檔案或空間使用量的技術。此資源類型隨ONTAP 附於NetApp 9.6。

.配額規則
用於強制執行配額的規則。此資源類型採用ONTAP 了更新ONTAP 版的32個版本、更新版為32個版本。

.磁碟櫃
叢集中的磁碟櫃。此資源類型隨ONTAP 附於NetApp 9.6。

.Snapshot原則
快照是根據原則建立。此資源類型隨ONTAP 附於NetApp 9.6。

.Snapshot排程
您可以控制快照排程。此資源類型是ONTAP 全新重新設計的、採用了NetApp 9.8。

.交換器
您可以擷取叢集中的交換器。此資源類型隨ONTAP 附於引用的資料檔9.9。

.磁帶設備
您可以擷取叢集中的磁帶設備。此資源類型隨ONTAP 附於引用的資料檔9.9。

.頂尖指標
頂端度量端點可讓您決定依特定度量篩選之磁碟區的活動。您可以根據用戶端、目錄、檔案和使用者來進行篩選。此資源類型隨ONTAP 附於引用的功能不只是功能。9.10。

.Volume效率原則
您可以使用這些API呼叫來設定套用至整個Volume的效率。此資源類型是ONTAP 更新的功能、採用了更新的功能。

.磁碟區
邏輯容器用於將資料提供給用戶端。此資源類型最初是以ONTAP 不含REST API的功能推出。API所使用的許多參數值都已透過ONTAP 包含空間管理的值在內的各個方面、大幅擴充。

.Volume檔案
您可以擷取磁碟區上特定目錄的檔案和目錄清單。此資源類型是以ONTAP 更新ONTAP 版本的更新版本介紹、並以更新版本的更新版本為更新版本。

.Volume Snapshot
Volume的快照。此資源類型隨ONTAP 附於NetApp 9.6。
