---
sidebar: sidebar 
permalink: resources/support.html 
keywords:  
summary:  
---
= 支援
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用這些API呼叫來管理ONTAP 用來支援叢集的功能。



==== 自動更新

自動更新功能ONTAP 可下載並套用最新的軟體更新、讓您的整個系統保持最新狀態。有多種端點類別可支援此功能、包括狀態、組態和更新。這些資源類型是ONTAP 以引用的功能為參考9.10。



==== AutoSupport

NetApp會收集組態與狀態的詳細資料及錯誤、並將資訊報告給NetApp。AutoSupport此資源類型隨ONTAP 附於NetApp 9.6。



==== 資訊AutoSupport

每個節點都會維護AutoSupport 可產生及擷取的各項資訊。此資源類型隨ONTAP 附於NetApp 9.6。



==== 組態備份

您可以使用這些API來擷取及更新目前的備份設定。此資源類型隨ONTAP 附於NetApp 9.6。



==== 組態備份作業

您可以建立、擷取及刪除組態備份檔案。此資源類型隨ONTAP 附於NetApp 9.7。



==== 核心傾印

您可以使用這些端點來擷取及管理叢集或節點產生的記憶體核心傾印。此資源類型隨ONTAP 附於引用的功能不只是功能。9.10。



==== EMS

事件管理系統（EMS）會收集事件、並將通知傳送至一或多個目的地。此資源類型隨ONTAP 附於NetApp 9.6。



==== EMS目的地

EMS目的地會決定通知的傳送方式和傳送位置。此資源類型隨ONTAP 附於NetApp 9.6。



==== EMS目的地執行個體

EMS目的地執行個體是依類型和位置定義。此資源類型隨ONTAP 附於NetApp 9.6。



==== EMS活動

這是叢集的系統事件即時集合。此資源類型隨ONTAP 附於NetApp 9.6。



==== EMS篩選器

EMS篩選器可共同識別需要額外處理的事件。此資源類型隨ONTAP 附於NetApp 9.6。



==== EMS會篩選執行個體

EMS篩選執行個體是套用至事件的規則集合。此資源類型隨ONTAP 附於NetApp 9.6。



==== EMS訊息

提供對EMS事件目錄的存取。此資源類型隨ONTAP 附於NetApp 9.6。



==== 篩選執行個體的EMS規則

可針對EMS篩選器的特定執行個體管理規則清單。此資源類型隨ONTAP 附於NetApp 9.6。



==== 篩選執行個體的EMS規則執行個體

EMS篩選器特定執行個體的個別規則。此資源類型隨ONTAP 附於NetApp 9.6。



==== SNMP

您可以啟用和停用叢集的SNMP和設陷作業。此資源類型隨ONTAP 附於NetApp 9.7。



==== SNMP設陷主機

SNMP設陷主機是一種系統、設定為從ONTAP 功能區接收SNMP設陷。您可以擷取及定義主機。此資源類型隨ONTAP 附於NetApp 9.7。



==== SNMP設陷主機執行個體

您可以管理特定的SNMP設陷主機。此資源類型隨ONTAP 附於NetApp 9.7。



==== SNMP使用者

您可以定義及管理SNMP使用者。此資源類型隨ONTAP 附於NetApp 9.7。



==== SNMP使用者執行個體

您可以管理引擎ID與管理SVM或資料SVM相關聯的特定SNMP使用者。此資源類型隨ONTAP 附於NetApp 9.7。
