---
sidebar: sidebar 
permalink: migrate/migration-considerations.html 
keywords: migrate, mirgate to rest api, snapdiff 
summary: 在從 ONTAPI API （ ZAPI ）或 ONTAP CLI 移轉至 ONTAP REST API 之前、您應該考慮幾個問題。 
---
= 移轉考量
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在從 ONTAPI API （ ZAPI ）或 ONTAP CLI 移轉至 ONTAP REST API 之前、您應該考慮幾個問題。



== 一般設計差異

此產品的設計與功能完全不同、ONTAPCLI命令和參數不會直接對應至REST API呼叫。即使可能有相似性、輸入參數的詳細資料也可能有所不同。例如、數字單位可能是以位元組為單位指定、或是使用字尾（例如KB）。請參閱 link:../rest/input_variables.html["控制API要求的輸入變數"] 和 link:../reference/api_reference.html["API 參考"] 以取得更多資訊。



== 透過REST API公開的資料SVM

支援多種儲存虛擬機器（SVM）ONTAP 。不過ONTAP 、只有資料SVM會透過REST API直接曝露在外。說明叢集和節點的組態資訊可透過REST API取得、但是叢集和節點不會視為個別的SVM。



== 透過REST API存取ONTAP REST CLI

為了協助 ONTAPI API 和 CLI 使用者轉換至 ONTAP REST API 、 ONTAP 提供 REST 端點以存取 ONTAP CLI 。您可以使用此傳遞功能來執行任何CLI命令。  其餘端點的使用會傳回 AutoSupport 資料、讓 NetApp 能夠識別 REST API 中的落差、並在未來的 ONTAP 版本中進行改善。

若要發出 CLI 命令、您必須根據下列相關規則、撥打適當格式的 REST API 呼叫：

* 資源路徑
* 欄位名稱
* HTTP方法


CLI 存取的基礎資源路徑為 `/private/cli`。如ONTAP 需透過REST API存取CLI的詳細資訊、請參閱《靜態API》線上文件頁面。NetApp 也維護 GitHub 儲存庫、其中包含程式碼範例和其他實用資訊。請參閱 https://github.com/NetApp/ontap-rest-python/tree/master/examples/rest_api/cli_passthrough_samples["靜態Python GitHub儲存庫- CLI傳遞範例ONTAP"^] 以取得更多資訊。



== 在ONTAPI中對SnapDiff可用度所做的變更

從ONTAP 功能性版本的E59.10.1開始、SnapDiff v1和v2 ONTAPI呼叫將無法叫用。任何啟動SnapDiff v1或v2 ONTAPI呼叫的第三方應用程式、都無法從ONTAP 版本資訊的版本9.10.1開始運作。支援SnapDiff v3 REST的備份應用程式、使用者應先確認其是否支援、再升級至版本RE-9.10.1。ONTAP ONTAP

SnapDiff API在ONTAP 整個發行版中的可用度定義如下：

* 更新版本：V1和v2（僅限ONTAPI）ONTAP
* 資料9.8–9.9.1：V1、v2和v3（ONTAPI和REST API）ONTAP
* ONTAP 9 ． 10.1 及更新版本：僅 v3 （僅限 REST API ）


另請參閱 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["發行說明 ONTAP"^] 以取得更多資訊。



== 提交您的 ONTAPI 以消除 API 的落差

NetApp 致力於支援客戶從 ONTAPI 移轉至 ONTAP REST API 。如果您注意到 REST API 中缺少某些內容、請通知我們。您可以在上提交這些落差和任何其他想法 https://forms.office.com/Pages/ResponsePage.aspx?id=oBEJS5uSFUeUS8A3RRZbOtlEKM3rNwBHjLH8dubcgOVURVM2UzIzTkQzSzdTU0pQRVFFRENZWlAxNi4u["用於 REST API 的 ONTAPI"^] 頁面。
