---
sidebar: sidebar 
permalink: migrate/software.html 
keywords:  
summary:  
---
= 工具與軟體
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp 提供 Python 指令碼範例和其他相關軟體、以支援您從 ONTAPI 移轉至 ONTAP REST API 。以下說明這些樣本中最重要的部分。


NOTE: 所有 Python 程式碼範例均可在 GitHub 儲存庫取得 https://github.com/NetApp/ontap-rest-python["NetApp ONTAP REST Python"^]。您也應該檢閱中的可用資源link:../additional/learn_more.html["深入瞭解 ONTAP REST API"]。



== ONTAPI 使用報告工具

ONTAPI 使用報告工具旨在協助 NetApp 專業服務、客戶及合作夥伴識別其 ONTAP 環境中的 ONTAPI 使用情形。下表說明三種不同使用案例的指令碼。

[cols="20,80"]
|===
| 指令碼 | 說明 


| apache_scraper.py | Apache 記錄剪貼簿、可尋找針對 ONTAP 節點發出的 ONTAPI 呼叫 


| session_stats.py | 從 ONTAP 擷取工作階段統計資料的 CLI 指令碼 


| zapi_to_rest.py | 擷取所傳遞之 ONTAPI 呼叫和屬性其餘詳細資料的指令碼 
|===
您可以存取 https://github.com/NetApp/ontap-rest-python/tree/master/ONTAPI-Usage-Reporting-Tool["ONTAPI 使用報告工具"^] 開始使用。另請參閱 A https://www.youtube.com/watch?v=gJSWerW9S7o["示範"^] 關於報告工具及其使用方法。



== 專用 CLI 傳遞

其餘 API 則涵蓋 ONTAP 提供的功能與設施。不過、在某些情況下、透過 REST API 直接存取 ONTAP CLI 可能會很有用。

如需此功能的簡介、請參閱 link:../rest/access_ontap_cli.html["透過REST API存取ONTAP REST CLI"]。如需 Python 範例、請參閱 https://github.com/NetApp/ontap-rest-python/tree/master/examples/rest_api/cli_passthrough_samples["REST CLI 傳遞範例"^]。



== Python用戶端程式庫

Python 用戶端程式庫是一個套件、您可以安裝並使用它來存取 ONTAP REST API 搭配 Python 。它可讓您快速開發健全的程式碼、以自動化 ONTAP 部署。若要深入瞭解 Python 用戶端程式庫，請參閱link:../python/learn-about-pcl.html["Python用戶端程式庫"]。



== ONTAP PowerShell 工具套件

NetApp.ONTAP PowerShell Toolkit 以包含超過 2 、 400 個 Cmdlet 的模組來強化您的本機 PowerShell 環境。它可讓您快速開發 Windows 主機的程式碼、以自動化 ONTAP 部署。如需詳細資訊、請參閱 link:../pstk/overview_pstk.html["PowerShell 工具套件概觀"]。
