---
sidebar: sidebar 
permalink: additional/learn_more.html 
keywords: learn, learn more, more information, additional resources 
summary: 您可以存取其他幾項資源、以取得協助、並取得有關如何自動化ONTAP 部署及管理您的不必要儲存系統的更多資訊。 
---
= 深入瞭解 ONTAP REST API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
有幾種額外資源可協助您自動化 ONTAP 儲存系統的部署與管理。



== 部落格文章

部落格文章會根據主題分為幾個部分。



=== 一般

* 目前 ONTAP 自動化技術的良好摘要。
+
https://www.netapp.com/blog/new-normal-for-automation["自動化的新常態"^]

* 您可以監控 ONTAP 事件、隨時掌握系統活動。這些事件的組態和管理可以使用 REST API 自動進行。
+
https://blog.netapp.com/ontap-rest-apis-automate-notification["REST API：自動通知高嚴重性事件ONTAP"^]

* 休息時間（ 6 集）：
+
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-1-Basics-of-ONTAP-REST-APIs/m-p/167852["ONTAP REST API 的基礎知識"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-2-Features-of-ONTAP-REST-APIs/m-p/168168/highlight/true#M208["ONTAP REST API 的功能"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-3-Getting-Hands-on-with-ONTAP-REST-using-Postman/m-p/431965/highlight/true#M283["使用 Postman 實際操作 ONTAP REST"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-4-ONTAPI-ZAPI-Reporting-tool/m-p/433200["ONTAPI （ ZAPI ）報告工具"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-5-Private-CLI-Passthrough/m-p/435293["專用 CLI Passthrough"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-6-5-magical-features-that-make-ONTAP-storage/m-p/435604["讓 ONTAP 儲存自動化變得簡單的 5 項神奇功能！"^]






=== Python用戶端程式庫

* 此部落格提供 ONTAP Python 用戶端程式庫功能的良好簡介。
+
https://www.netapp.com/blog/simplify-ontap-rest-api-consumption["使用 Python 用戶端程式庫簡化 ONTAP REST API 的使用"^]





=== 移轉至 REST API

* 有幾項技術可協助您根據ONTAP REST API來改造您的非自動化環境。
+
https://www.netapp.com/blog/transform-automation-ontap-rest-api/["將自動化技術從ONTAP ONTAPI轉型為靜態API"^]





== 影片

* NetApp Python 用戶端程式庫的良好簡介、以及如何開始使用程式庫撰寫程式碼。
+
video::pg5ls1Ol6uw[youtube,width=848,height=480]
* 瞭解 Ansible 認證模組。
+
video::ZlmQ5IuVZD8[youtube,width=848,height=480]
+
video::L5DZBV_Sg9E[youtube,width=848,height=480]
* NetApp TechComm TV 上的一系列影片。
+
https://www.youtube.com/playlist?list=PLHSh2r3A9gQRG1kkAcx1MmtVYPimyxOp_["自動化 NetApp ONTAP 管理"^]





== NetApp知識庫

* 如果 ONTAP REST API 發生問題、您可以將其回報給 NetApp 。
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_report_REST_API_and_NetApp_Python_Module_(REST_API_via_python_module)_issues["如何回報 ONTAP REST API 和 ONTAP REST API Python 用戶端程式庫的問題"^]

* 如果您在 ONTAP REST API 中發現功能落差、則可以要求 API 的新功能。
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_request_a_feature_for_ONTAP_REST_API["如何申請 ONTAP REST API 的功能"^]


