---
sidebar: sidebar 
permalink: sw-tools/nmsdk.html 
keywords: netapp manageability sdk, oncommand workflow automation, oncommand wfa, ontapi, ontap rest api 
summary: NetApp Manageability SDK 提供一組 ONTAPI API 呼叫、用於開發應用程式來監控及管理您的 ONTAP 儲存設備。SDK 搭配 OnCommand Workflow Automation 套件、可協助您將 ONTAP 系統的管理作業自動化。 
---
= NetApp Manageability SDK
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Manageability SDK 提供一組 ONTAPI API 呼叫、用於開發應用程式來監控及管理您的 ONTAP 儲存設備。SDK 搭配 OnCommand Workflow Automation 套件、可協助您將 ONTAP 系統的管理作業自動化。


NOTE: 雖然 NetApp Manageability SDK 和 OnCommand Workflow Automation 持續受到支援、但 ONTAP REST API 是自動化 ONTAP 系統時首選使用的策略性技術。請參閱 link:../migrate/ontapi_disablement.html["ONTAPI 停用"] 以取得更多資訊。

.下載 SDK
您可以從 NetApp 支援網站 下載 NetApp Manageability SDK 。SDK 支援用戶端上的多種語言、包括： Python 、 PowerShell 、 C 、 C++ 、 Java 、 C# 、 VB. NET 和 Ruby 。請務必檢閱互通性對照表工具、以取得 NetApp Manageability SDK 的相關資訊、以及您的 ONTAP 版本如何支援該工具。

.使用 OnCommand Workflow Automation
您也可以使用 SDK 隨附的 API 來自動化管理工作、而無需撰寫任何指令碼。OnCommand Workflow Automation （ OnCommand WFA ）提供數個預先封裝的工作流程、以部署及執行管理工作。您可以從 NetApp 儲存自動化商店下載 OnCommand WFA 套件。

.相關資訊
* https://mysupport.netapp.com/site/["NetApp 支援網站"^]
* https://www.netapp.com/company/interoperability/["NetApp 互通性對照表工具"^]
* https://mysupport.netapp.com/documentation/docweb/index.html?productID=63638&language=en-US["NetApp Manageability SDK 文件"^]
* https://www.netapp.com/data-management/oncommand-workflow-automation-documentation/["OnCommand Workflow Automation 文件資源"^]
* https://automationstore.netapp.com/home.shtml["NetApp Automation Store"^]

