---
sidebar: sidebar 
permalink: get-started/access_rest_api.html 
keywords: access rest api, lif, cluster lif, svm lif, node lif 
summary: 您可以ONTAP 使用多種不同的方法來存取靜態API。 
---
= 如何存取ONTAP 靜態API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以ONTAP 使用多種不同的方法來存取靜態API。



== 網路考量

您可以使用多種類型的介面之一連接到ONTAP REST API。您選擇的 LIF 需要設定為支援 HTTPS 管理協定。此外，您網路中的防火牆配置必須允許 HTTPS 流量。支援以下介面：

* 叢集管理LIF
* 節點管理 LIF
* SVM管理LIF


雖然您可以使用這些 LIF 中的任何一個，但建議的最佳實踐是使用叢集管理 LIF。這樣一來，叢集就可以作為一個單一的邏輯單元進行定址，從而提供最高層級的彈性和負載平衡。集群 LIF 可以根據需要重新定位到集群中，以處理計劃內的升級、仲裁事件和其他連接問題。如果配置了多個叢集管理 LIF，它們在存取 REST API 方面都是等效的。SVM 管理 LIF 也進行了負載平衡，但傳送到節點層級 LIF 的請求會在本地處理。



== 介紹API線上文件頁面ONTAP

使用網頁瀏覽器時、「支援API」線上文件頁面提供存取點。ONTAP除了提供直接執行個別API呼叫的方法、此頁面還包含API的詳細說明、包括每個呼叫的輸入參數和其他選項。API呼叫分為功能類別。請參閱 link:../resources/overview_categories.html["剩餘資源摘要"] 以取得更多資訊。

用於存取API最新版本文件頁面的URL格式為：

`\https://<cluster_mgmt_ip_address>/docs/api`



== 自訂軟體與工具

您可以ONTAP 使用多種不同的程式設計語言和工具來存取VMware API。熱門選項包括Python、Java、Curl和PowerShell。使用API的程式、指令碼或工具會做為REST Web服務用戶端。使用程式設計語言可更深入瞭解API、並提供自動化ONTAP 的機會來進行支援。

用於直接存取最新版API的基礎URL格式如下：

`\https://<cluster_mgmt_ip_address>/api`

若要存取支援多個版本的特定API版本、URL格式如下：

`\https://<cluster_mgmt_ip_address>/api/v1`
