---
sidebar: sidebar 
permalink: get-started/ontap_automation_options.html 
keywords: ontap automation, rest api, python client library, powershell, ansible, bluexp automation catalog, netapp, console 
summary: 有幾個選項可用於自動化 ONTAP 儲存系統的部署與管理。 
---
= 瞭ONTAP 解功能自動化選項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
有幾個選項可用於自動化 ONTAP 儲存系統的部署與管理。



== 靜態API ONTAP

從ONTAP 9.6 開始， ONTAP包含一個強大的 REST API，為自動部署和管理儲存系統奠定了基礎。從那時起，REST API 不斷擴展和成熟。現在，它在自動化ONTAP部署管理時提供了首選和策略性的選擇。

.原生存取 REST API
您可以ONTAP 使用任何支援REST用戶端的程式設計語言、直接存取靜態API。熱門的語言選擇包括Python、PowerShell和Java。

.移轉舊版的 ONTAPI 程式碼以使用 REST
ONTAPI API（Zephyr API 或 ZAPI）是NetApp ONTAP軟體中包含的原始專有呼叫集，用於支援資料儲存管理和管理任務的自動化。 API 是link:../sw-tools/learn-about-nmsdk.html["NetApp Manageability SDK"]。如果您現有的程式碼使用 ONTAPI API，則應排程遷移至ONTAP REST API，以利用 REST API 提供的擴充功能集。 NetApp提供將您的程式碼轉換為使用較新的ONTAP REST API 的支援。看link:../migrate/migration-considerations.html["從 ONTAPI 移轉至 REST API"]了解更多。



== 用戶端軟體工具套件

NetApp 提供用戶端工具套件、可抽象化 ONTAP REST API 、並讓建立自動化程式碼變得更容易。您應該選擇適合您開發語言和環境的選項。

.Python用戶端程式庫
Python用戶端程式庫是一個套件、您可以在寫入指令碼以存取ONTAP REST API時使用。它支援多種基礎服務、包括連線管理、非同步要求處理及例外處理。您可以使用Python用戶端程式庫、快速開發強大的程式碼來支援ONTAP 您的自動化目標。如需詳細資訊、請參閱 link:../python/learn-about-pcl.html["Python用戶端程式庫"] 。

.PowerShell 工具套件
您可以使用 NetApp.ONTAP PowerShell Toolkit 、從 Windows 主機自動管理 ONTAP 叢集。如需詳細資訊、請參閱 link:../pstk/learn-about-pstk.html["瞭解 NetApp PowerShell 工具套件"] 。



== 自動化架構

您可以使用多個框架之一來建立和部署自動化程式碼。

.Ansible
Ansible是開放原始碼軟體工具、可支援資源配置、組態管理及應用程式部署。自從RedHat推出及後續併購之後、它的受歡迎度持續成長。NetApp提供獲認證的Ansible模組、客戶可用來自動化ONTAP 其支援的整套系統管理。請參閱 link:../additional/learn_more.html["深入瞭解"] 和 https://www.netapp.com/devops-solutions/ansible/["NetApp Ansible DevOps解決方案"^] 以取得更多資訊。

.NetApp控制台自動化目錄
NetApp https://console.netapp.com/automationCatalog/["NetApp控制台自動化目錄"^]可透過控制台 Web 使用者介面存取。該目錄提供對打包解決方案的訪問，可幫助您自動部署ONTAP並將其與其他產品整合。看 https://docs.netapp.com/us-en/netapp-automation/["NetApp 自動化"^]以取得文件和更多資訊。
