---
sidebar: sidebar 
permalink: rest/object_references_and_access.html 
keywords: objects, access paths, uuid, uuidv4, collections, object collection 
summary: 透過REST API曝光的資源執行個體或物件ONTAP 、可透過多種不同的方式進行參考和存取。 
---
= 物件參考與存取
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
透過REST API曝光的資源執行個體或物件ONTAP 、可透過多種不同的方式進行參考和存取。



== 物件存取路徑

在較高層級、存取物件時有兩種路徑類型：

* 主要
+
物件是API呼叫的主要或直接目標。

* 國外
+
物件不是API呼叫的主要參考、而是從主要物件連結至。因此、它是外部或下游物件、並透過主要物件的欄位加以參照。





== 使用UUID存取物件

每個物件在建立時都會指派一個唯一的識別碼、在大多數情況下是128位元UUID。指派的UUID值不可改變、可在ONTAP 內部用於存取及管理資源。因此、UUID通常是存取物件的最快且最穩定的方法。

對於許多資源類型、可以在URL中提供UUID值作為路徑金鑰的一部分、以存取特定物件。例如、您可以使用下列項目來存取節點執行個體：「/叢集/節點/｛uuid｝」



== 使用物件內容存取物件

除了UUID之外、您也可以使用物件內容來存取物件。在大多數情況下、使用name屬性很方便。例如、您可以在URL字串中使用下列查詢參數、以名稱存取節點執行個體：「/cluster / nodes?name=node_on'。除了查詢參數之外、外部物件也可透過主要物件的屬性存取。

雖然您可以使用名稱或其他屬性來存取物件、而非UUID、但仍有幾個可能的缺點：

* 名稱欄位並非不可變更的欄位、可以變更。如果在存取物件之前變更物件名稱、將會傳回錯誤的物件、否則物件存取錯誤將會失敗。
+

NOTE: 此問題可能發生於外部物件上的POST或修補方法、或是主要物件上的Get方法。

* 必須將名稱欄位轉譯為對應的UUID。ONTAP這是一種間接存取、可能會成為效能問題。


尤其是當下列一項或多項條件成立時、效能可能會降低：

* 使用Get方法
* 系統會存取大量物件集合
* 使用複雜或精細的查詢




== 叢集與SVM內容

有幾個REST端點同時支援叢集和SVM。使用其中一個端點時、您可以透過「shcope=[SVM|cluster」（叢集）值來指出API呼叫的內容。支援雙內容的端點範例包括IP介面和安全角色。


NOTE: 範圍值會根據每個API呼叫所提供的內容、提供預設值。



== 在物件集合上使用修補程式和刪除

支援資源執行個體上修補或刪除的每個REST端點、也支援物件集合上的相同方法。唯一的需求是必須透過URL字串中的查詢參數提供至少一個欄位。在發佈修補程式或刪除集合時、這相當於在內部執行下列動作：

* 以查詢為基礎的Get來擷取集合
* 修補或刪除集合中每個物件上的呼叫的序列順序


作業的逾時時間可設定為預設為15秒的「恢復逾時」。如果在逾時之前未完成、回應會包含下一個物件的連結。您必須使用下一個連結重新核發相同的HTTP方法、才能繼續作業。
