---
sidebar: sidebar 
permalink: rest/operational_characteristics.html 
keywords: operation, request and response, crud 
summary: 您可以ONTAP 使用多種不同的方法來存取靜態API。 
---
= 基本營運特性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
REST建立一套通用的技術和最佳實務做法、但每個API的詳細資料可能會因設計選項而異。



== 要求及回應API交易

每次REST API呼叫都會以HTTP要求的形式執行ONTAP 、以產生與用戶端相關的回應。此要求/回應配對被視為API交易。在使用API之前、您應該先熟悉可用於控制要求的輸入變數、以及回應輸出的內容。



== 支援CRUD作業

透過「REST API」提供的每項資源ONTAP 、都是根據CRUD模式來存取：

* 建立
* 讀取
* 更新
* 刪除


對於某些資源、只支援一部分作業。您應該檢閱ONTAP 位於您的叢集上的「ENetApp API」文件頁面ONTAP 、以取得每項資源的詳細資訊。



== 物件識別碼

每個資源執行個體或物件在建立時都會指派一個唯一的識別碼。在大多數情況下、識別碼為128位元UUID。這些識別碼在特定ONTAP 的支援中心叢集內是全域唯一的。發出API呼叫以建立新的物件執行個體之後、會在HTTP回應的位置標頭中、傳回具有相關ID值的URL給呼叫者。您可以擷取識別碼、並在參照資源執行個體時用於後續通話。


NOTE: 物件識別碼的內容和內部結構可隨時變更。當您參照相關的物件時、只能視需要在適用的API呼叫上使用識別碼。



== 物件執行個體和集合

根據資源路徑和HTTP方法、API呼叫可套用至特定物件執行個體或物件集合。



== 同步與非同步作業

執行從用戶端收到的HTTP要求有兩種方式ONTAP 。

同步處理:: 如果HTTP狀態代碼為200或201（成功）、則會立即執行要求、並以HTTP狀態代碼回應。ONTAP
+
--
使用方法Get、head和options的每個要求都會一律同步執行。此外、使用POST、修補及刪除的要求、設計為在預期不到兩秒內完成時同步執行。

--
非同步處理:: 如果非同步要求有效、ONTAP 則會建立背景工作來處理要求、並建立工作物件來固定工作。這會將202 HTTP狀態連同工作物件傳回給呼叫者。若要判斷最終成功或失敗、您必須擷取工作狀態。
+
--
使用POST、修補和刪除方法的要求、是設計成在預期需要兩秒以上才能完成時、非同步執行。


NOTE: 「RETON_Timeout」查詢參數可用於非同步API呼叫、並可將非同步呼叫轉換為同步完成。如需詳細資訊、請參閱「使用工作物件進行非同步處理的方式」。

--




== 安全性

REST API所提供的安全性主要是以ONTAP 現有的資訊安全功能為基礎。API使用下列安全性：

* 傳輸層安全性
+
透過網路在ONTAP S還原LIF與用戶端之間傳送的所有流量、通常會根據ONTAP 還原組態設定、使用TLS加密。

* 用戶端驗證
+
使用相同的驗證選項ONTAP 、也可以搭配使用搭配使用《Rsest ONTAP API》（《Rsest System Manager》）和《Network Manageability SDK》（網路管理SDK）。

* HTTP驗證
+
在HTTP層級、API交易會使用基本驗證。每個要求都會新增一個HTTP標頭、其中使用者名稱和密碼為基礎64字串。

* 驗證ONTAP
+
執行角色型授權模式。ONTAP您在存取ONTAP 「靜態API」或API文件頁面時所使用的帳戶、應有適當的權限。


