---
sidebar: sidebar 
permalink: rest/rbac_sample_roles.html 
keywords:  
summary:  
---
= 角色定義範例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
根據您的環境、您可以使用不同的方式來使用此功能。ONTAP以下是一些常見案例。在每個案例中、重點都是特定的安全性和管理目標、以及對應角色定義的範例。


NOTE: 所有的範例都使用「/API/SECE/DIRS/DIRS/角色」和衍生的REST端點來建立和修改角色。為了清楚說明、每個Curl命令都是指個別的Json輸入檔。



== 限制對SVM Volume作業的存取

您可能想要限制SVM內的儲存磁碟區管理。以下範例以先建立並選擇性更新的角色來說明這一點。



=== 建立初始角色

系統會建立傳統角色、以便一開始存取除複製以外的所有主要Volume管理功能。以下所示角色的定義具有下列特定特性：

* 能夠執行所有CRUD Volume作業、包括Get、Create、Modify和Delete
* 無法建立Volume複製


.Curl範例
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.JSONN輸入範例
[source, json]
----
{
  "name": "role1",
  "owner": {
    "name": "cluster-1",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      { "path": "volume create", "access": "all" },
      { "path": "volume delete", "access": "all" }
    ]
}
----


=== 更新角色

可以修改相同的角色、讓使用者也能建立Volume Clone。

.Curl範例
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles/852d96be-f17c-11ec-9d19-005056bbad91/role1/privileges' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.JSONN輸入範例
[source, json]
----
{
  "path": "volume clone",
  "access": "all"
}
----


== 資料保護管理

在某些情況下、您可能想要為使用者提供有限的資料保護功能。以下所示的傳統角色具有下列特性：

* 能夠建立和刪除快照、以及更新SnapMirror關係
* 無法建立或修改較高層級的物件、例如磁碟區或SVM


.Curl範例
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.JSONN輸入範例
[source, json]
----
{
  "name": "role1",
  "owner": {
    "name": "cluster-1",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      {"path": "volume snapshot create", "access": "all"},
      {"path": "volume snapshot delete", "access": "all"},
      {"path": "volume show", "access": "readonly"},
      {"path": "vserver show", "access": "readonly"},
      {"path": "snapmirror show", "access": "readonly"},
      {"path": "snapmirror update", "access": "all"}
  ]
}
----


== 產生ONTAP 功能報告

您可以建立REST角色、讓使用者能夠產生ONTAP 各種報告。以下所示職務的定義特性如下：

* 能夠擷取與容量和效能相關的所有儲存物件資訊（例如Volume、qtree、LUN、Aggregate、節點、 和SnapMirror關係）
* 無法建立或修改較高層級的物件（例如磁碟區或SVM）


.Curl範例
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.JSONN輸入範例
[source, json]
----
{
  "name": "rest_role1",
  "owner": {
    "name": "cluster-1",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      {"path": "/api/storage/volumes", "access": "readonly"},
      {"path": "/api/storage/qtrees", "access": "readonly"},
      {"path": "/api/storage/luns", "access": "readonly"},
      {"path": "/api/storage/aggregates", "access": "readonly"},
      {"path": "/api/cluster/nodes", "access": "readonly"},
      {"path": "/api/snapmirror/relationships", "access": "readonly"},
      {"path": "/api/svm/svms", "access": "readonly"}
  ]
}
----