---
permalink: manage/ems-rest-api.html 
sidebar: sidebar 
keywords: ems, configuration, workflow 
summary: 使用REST API管理EMS組態。 
---
= 利用REST API管理EMS事件通知ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP Sesrest API來設定事件管理系統（EMS）事件通知傳送給您的重要性、以及擷取具有特定屬性的所有EMS訊息或特定訊息。您可以使用REST API來協助自動化與EMS相關的工作、節省使用其他EMS訊息方法的時間。

以下範例說明如何使用ONTAP Resrest API來處理EMS訊息。在每個範例中、請務必在方括弧<>中指定資訊的值。您也可以參考範例 https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/events.py["Python指令碼"^] 這說明如何將許多與EMS相關的活動自動化。



== 檢視特定事件記錄

使用「Get /support/ES/events」API呼叫、您可以擷取特定事件訊息、例如最新訊息、包含特定文字的訊息、或是具有特定嚴重性的訊息。

.申請範例：擷取最新訊息
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems/events?fields=message.name&max_records=1'
----
.回應範例
[source, json]
----
"records": [
    {
      "node": {
        "name": "malha-vsim1",
        "uuid": "da4f9e62-9de3-11ec-976a-005056b369de",
        "_links": {
          "self": {
            "href": "/api/cluster/nodes/da4f9e62-9de3-11ec-976a-005056b369de"
          }
        }
      },
      "index": 6260,
      "message": {
        "name": "netinet6.rtr.high.mtu"
      },
      "_links": {
        "self": {
          "href": "/api/support/ems/events/malha-vsim1/6260"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/support/ems/events?fields=message.name&max_records=1"
    },
    "next": {
      "href": "/api/support/ems/events?start.keytime=2022-03-22T10%3A28%3A29-04%3A00&start.node.name=malha-vsim1&start.index=6260&fields=message.name&max_records=1"
    }
  }
}
----
.申請範例：擷取內含特定文字和嚴重性的訊息
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems/events?log_message=*disk*&message.severity=alert'
----
.回應範例
[source, json]
----
"records": [
    {
      "node": {
        "name": "malha-vsim1",
        "uuid": "da4f9e62-9de3-11ec-976a-005056b369de",
        "_links": {
          "self": {
            "href": "/api/cluster/nodes/da4f9e62-9de3-11ec-976a-005056b369de"
          }
        }
      },
      "index": 4602,
      "time": "2022-03-18T06:37:46-04:00",
      "message": {
        "severity": "alert",
        "name": "raid.autoPart.disabled"
      },
      "log_message": "raid.autoPart.disabled: Disk auto-partitioning is disabled on this system: the system needs a minimum of 4 usable internal hard disks.",
      "_links": {
        "self": {
          "href": "/api/support/ems/events/malha-vsim1/4602"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/support/ems/events?log_message=*disk*&message.severity=alert&max_records=1"
    },
    "next": {
      "href": "/api/support/ems/events?start.keytime=2022-03-18T06%3A37%3A46-04%3A00&start.node.name=malha-vsim1&start.index=4602&log_message=*disk*&message.severity=alert"
    }
  }
}
----


== 檢視現有的EMS組態

使用「Get /support/ES/」API呼叫、您可以擷取現有EMS通知組態的相關資訊。

.申請範例
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems/'
----
.回應範例
[source, json]
----
{
  "proxy_url": "https://proxyserver.mycompany.com",
  "proxy_user": "proxy_user",
  "mail_server": "mail@mycompany.com",
  "_links": {
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "pubsub_enabled": "1",
  "mail_from": "administrator@mycompany.com"
}
----


== 建立新的EMS通知組態

您可以同時使用數個API呼叫來建立新的EMS組態、以自訂接收訊息的方式和時間。

.步驟
. 設定全系統的電子郵件設定。例如：
+
[source, curl]
----
curl -X PATCH -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/support/ems?mail_from=administrator@mycompany.com&mail_server=mail@mycompany.com'
----
. 定義使用特定規則來符合特定訊息的篩選條件。例如：
+
[source, curl]
----
curl -u admin:<PASSWORD> -X POST -d '{"name": "test-filter", "rules.type": ["include"], "rules.message_criteria.severities": ["emergency"]}' -k 'https://<IP_ADDRESS>/api/support/ems/filters/'
----
. 建立訊息的目的地。例如：
+
[source, curl]
----
curl -u admin:<PASSWORD> -X POST -d '{"name": "test-destination", "type": "email", "destination": "administrator@mycompany.com", "filters.name": ["important-events"]}' -k 'https://<IP_ADDRESS>/api/support/ems/destinations/'
----




== 不只是使用靜態API、更是使用非靜態CLI命令ONTAP ONTAP

利用此功能、您可以使用比支援許多工作的CLI更少的命令來自動化工作流程。ONTAP ONTAP例如、您可以使用單一POST API方法來建立篩選器、而非使用多個CLI命令。下表顯示完成一般EMS工作所需的CLI命令、以及對應的REST API呼叫：

|===
| 靜態API ONTAP | CLI ONTAP 


| 《Get /support/EMS》（取得/支援/EMS） | 「事件組態顯示」 


| "POST /support/ES/DESTINS/DESTINATION"  a| 
. 事件通知目的地建立
. 建立活動通知




| 《Get /support/ES/events》（取得/支援/緊急醫療服務/活動 | 「事件記錄顯示」 


| "POST /support/ES/filer"  a| 
. 「事件篩選器create -filter名稱<Filter name>」
. 「事件篩選規則add -filter名稱<Filter name>」


|===


== 相關資訊

* https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/events.py["靜態API EMS Python指令碼範例ONTAP"^]
* https://blog.netapp.com/ontap-rest-apis-automate-notification["REST API：自動通知高嚴重性事件ONTAP"^]

